### ISSUE TITLE
Seems that you cannot add status to a medical device

### ISSUE THREAD

**Issue by glpimedicuser** [delcroip/glpi_open_medis#21]
Even if you create a status where you indicate that medical devices are included in, you still can't add this status to a medical device because the status is registered without medical devices in.

**Comment by delcroip** [comment]
Hello,

on one of the version I had an issue because the "state" table was not amended (A column need to be added), I wrongly  though I added in the migration ....

I will create a migration 1.3 to add it

Br

**Comment by glpimedicuser** [comment]
Thank you for your help.

Br

**Comment by delcroip** [comment]
this is fixed on 1.0.1.rc4
