### ISSUE TITLE
Transfer issue from an entity to an other with medical devices

### ISSUE THREAD

**Issue by glpimedicuser** [delcroip/glpi_open_medis#24]
I can not transfer all my medical devices from my root entity to an other. But I don't think this issue can be solved by modifying the plugin but if I go wrong, is it possible to fix it ?

Br

**Comment by delcroip** [comment]
I'll check because it seems important to be possible

**Comment by delcroip** [comment]
here the solution with rc5

![Animation](https://user-images.githubusercontent.com/4052505/126899533-3f402646-ab5f-4a8c-8ffc-21810878322f.gif)
