### ISSUE TITLE
Display error when checking medical device informations

### ISSUE THREAD

**Issue by glpimedicuser** [delcroip/glpi_open_medis#40]
Hello, it's been a while,

Unfortunately, I'm writing to you because I'm encountering an issue when I want to inspect a medical device's informations. 
I can see his informations in the list :
![MDinList](https://user-images.githubusercontent.com/86647565/212102398-b7c1b74e-6b38-4fb0-8079-5f4e246b1ad1.PNG)

But when I inspect it, it no longer displays his Medical device informations :
![image](https://user-images.githubusercontent.com/86647565/212103897-a98df4e4-9d12-40e6-ae77-1b161046b9b2.png)

However, it still displays his Management informations and document(s) :
![image](https://user-images.githubusercontent.com/86647565/212104485-2d2b62c0-ad70-446b-a8bd-e18e1e2f87ab.png)

I have checked in my database that all the informations were corrects and there.
By the way, this issue appeared just after the update of our GLPI server from version 9.5.5 to 10.0.4
I'm also using the latest version of your plugin.
Is it possible that your latest version isn't adapted for this version of GLPI ?

**Comment by delcroip** [comment]
hi, 

I will try to check that tomorrow but did you take the version on the branch call 10 (specially made to work with version 10)?

https://github.com/delcroip/glpi_plugin_openmedis/tree/10.0

br

**Comment by glpimedicuser** [comment]
Hi,
Yes my bad, i just tried your version 10 and it resolved the problem.
Thanks for your help
