### ISSUE TITLE
Brand don't save

### ISSUE THREAD

**Issue by glpimedicuser** [delcroip/glpi_open_medis#42]
Saving after adding text in brand textbox clear it. No data saved.

**Comment by delcroip** [comment]
I double checked but I am not managing the saving (I just created the template, the core manage it)

But as you come from the first version of the module, the brand fields might not be in your DB, did  saving Brand on your server ever worked ? 

br

**Comment by glpimedicuser** [comment]
Hi,

Yes it worked before last updated, after cheking in database brand save well but it's not diplayed in glpi.

**Comment by delcroip** [comment]
should be fixed on branch 10
